name: Automatically create release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release:') && startsWith(github.head_ref, 'release/')
    container: registry.gitlab.com/islandoftex/images/texlive:TL2024-2024-05-19-full
    permissions:
      contents: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Set up Git as github-actions bot
      - name: Set up Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      # Run automated testing
      # extract files from dtx
      # build documentation
      # and package a .zip for ctan
      - name: Run l3build
        run: l3build ctan -q -H
        working-directory: ./rub-kunstgeschichte

      # Create tag with the new version
      - name: Get new version number
        id: get_new_version
        uses: ./.github/actions/get-release-version
        with:
          file: ./rub-kunstgeschichte/rub-kunstgeschichte.dtx
          class-name: rub-kunstgeschichte
      - name: Tag the commit
        run: |
          next_version=${{ steps.get_new_version.outputs.version }}
          git tag -a "$next_version" -m "$Version next_version. See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details."
          git push --follow-tags

      # Extract release notes from CHANGELOG.md
      - name: Extract release notes
        id: extract_release_notes
        run: |
          RELEASE_NOTES_PATH=${{ github.workspace }}/release_notes.md
          sed -n '/^## \[${{ steps.get_new_version.outputs.version }}\]/,/^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\]/ { /^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\]/ !p; }' CHANGELOG.md > $RELEASE_NOTES_PATH
          echo "release-notes-path=$RELEASE_NOTES_PATH" >> "$GITHUB_OUTPUT"

      # Create a GitHub release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_new_version.outputs.version }}
          name: Release ${{ steps.get_new_version.outputs.version }}
          body_path: ${{ steps.extract_release_notes.outputs.release-notes-path }}
          files: |
            rub-kunstgeschichte/build/unpacked/rub-kunstgeschichte.cls
            rub-kunstgeschichte/build/distrib/**/*.zip
            rub-kunstgeschichte/build/doc/*.pdf
            rub-kunstgeschichte/build/unpacked/rub-kunstgeschichte-example.tex