name: Automated testing and building

on:
  push:
    paths:
      - rub-kunstgeschichte/*.*
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main
    paths:
      - rub-kunstgeschichte/*.*
  workflow_dispatch:

jobs:
  l3build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    container: registry.gitlab.com/islandoftex/images/texlive:TL2024-2024-05-19-full
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Run automated testing
      # extract files from dtx
      # and build documentation
      - name: Run l3build
        run: l3build doc -q -H
        working-directory: ./rub-kunstgeschichte

      # Upload artifacts
      # Upload (main) documentation
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: rub-kunstgeschichte-manual.pdf
          path: rub-kunstgeschichte/rub-kunstgeschichte.pdf
      # Upload extracted class
      - name: Upload class
        uses: actions/upload-artifact@v4
        with:
          name: rub-kunstgeschichte.cls
          path: rub-kunstgeschichte/build/unpacked/rub-kunstgeschichte.cls
      # Upload example
      - name: Upload example tex file
        uses: actions/upload-artifact@v4
        with:
          name: rub-kunstgeschichte-example.tex
          path: rub-kunstgeschichte/build/unpacked/rub-kunstgeschichte-example.tex
      - name: Upload example pdf file
        uses: actions/upload-artifact@v4
        with:
          name: rub-kunstgeschichte-example.pdf
          path: rub-kunstgeschichte/rub-kunstgeschichte-example.pdf
            